### ISSUE TITLE
CI/CD - 테스트 코드 작성 및 자동 배포

### ISSUE THREAD

**Issue by sindydwns** [sindydwns/glance42#10]
- [ ] 각 함수 단위로 테스트 코드를 작성하고 커밋과 동시에 자동으로 테스트가 될 수 있는 환경을 만들어야 합니다. (CI)
- [ ] dev 및 master 브랜치에 커밋되면 테스트 완료 후 자동으로 배포될 수 있도록 해야합니다. (CD)

**Comment by niamu01** [comment]
dev서버 생기면 이어서 테스트 해볼 수 있습니다!

**Comment by JinmuGo** [comment]
dev 서버 만들다가 패닉이 왔네요..... 로컬에서 실행은 되는데 aws eb에 올라가면 에러가 뜹니다... 나중에 다시 시도해 봐야겠어요.
