### ISSUE TITLE
test 를 위한 association 수정

### ISSUE THREAD

**Issue by niamu01** [sindydwns/glance42#25]
associarion으로 연결된 테이블간의 관계가 테스트시 초기화 되지 않아 테이블 재생성에 오류가 나온다

**Comment by sindydwns** [comment]
이 이슈가 해결되면 #21 이슈도 이어서 처리할 수 있습니다!

**Comment by sindydwns** [comment]
연결된 db 환경에 따라 부분적으로 발생하는 문제인 것으로 보입니다. 기본적으로 mysql에서 외래키를 지원하지 않지만 일부 저장엔진에서는 지원한다고 합니다. 제 경우, sequelize.sync() 중에 planet scale로 db를 연결했을 경우 테이블을 생성할 수 없다는 에러가 발생했으며 리눅스환경에서 설치한 로컬db에서 이런 문제는 없었습니다.
