### ISSUE TITLE
이전 사용자의 view_id를 전역변수로 참조하는 문제. 

### ISSUE THREAD

**Issue by JinmuGo** [sindydwns/glance42#4]
slack bolt에서 렌더링을 할 때 view_id값을 참조해서 사용자에게 보여주는데 전역으로 view_id를 저장하는 바람에 다른 사용자의 페이지가 보이는 문제가 발생합니다.

**Comment by Yonaim** [comment]
모달 창에서 값을 submit할 시 callback에서 모달 창을 정상적으로 close하지 않고 저장된 이전의 view_id로 update하는 방식으로 화면을 렌더링하는 것이 문제였습니다.
모달 창의 submission이 완료될 시 실행되는 callback에서 모달 창을 정상적으로 close하고, 새로운 view를 publish함으로써 문제를 해결하였습니다. (update와 달리, publish는 view_id가 필요하지 않음)
