### ISSUE TITLE
슬랙 앱 레이아웃 수정

### ISSUE THREAD

**Issue by sindydwns** [sindydwns/glance42#6]
그룹에 멤버를 추가하기 위한 행동에 뎁스가 너무 깊습니다. 메인화면에서 선택된 그룹에 멤버를 추가하고 삭제하고 싶습니다.
~12/19

**Comment by Yonaim** [comment]
멤버 관리를 홈에서 한다면 selected_group 관련 문제도 해결이 가능합니다.
제가 처리하고 PR 올리겠습니다.
